###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:


    webserver:
        image: 'nginx:1.27.2-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - 'vendor:/application/app/third_party'
            - './composer.json:/application/composer.json'
            - './scripts/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '13100:80'

    php-fpm:
        build:
            context: ./
            dockerfile: ./scripts/phpdocker/php-fpm/Dockerfile
        working_dir: /application
        volumes:
            - '.:/application'
            - 'vendor:/application/app/third_party'
            - './composer.json:/application/composer.json'
            - './scripts/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
            - './scripts/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/cli/conf.d/99-overrides.ini'
volumes:
  vendor: